apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-backend
  template:
    metadata:
      labels:
        app: healthcare-backend
    spec:
      containers:
        - name: backend
          image: yourrepo/healthcare-backend:latest
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: healthcare-backend
  ports:
    - port: 5050
      targetPort: 5050